name: Publish

on:
  release:
    types: [created]

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 16
          registry-url: 'https://registry.npmjs.org'
          always-auth: true
          token: ${{ secrets.NPM_TOKEN }}
      - name: Install pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 7.25.1
          run_install: true
      - name: Build and publish
        run: |
          pnpm build
          pnpm publish --access public --no-git-checks
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
